config/routes.rb
Rails.application.routes.draw do
  get 'passanger/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :flights
  resources :bookings

  root "flights#index"
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :origin, foreign_key: 'origin_id', class_name: "Flight"
  has_many :destination, foreign_key: 'destination_id', class_name: "Flight"

  has_many :flights
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers, dependent: :destroy
  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  # Association between airport and airplane
  belongs_to :origin, class_name: "Airport"
  belongs_to :destination, class_name: "Airport"

  # Association between flight, booking, and passenger
  has_many :bookings, dependent: :destroy
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking

  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(allowed_post_params)
    if @booking.save
      redirect_to @booking, notice: "Your flight was successfully booked."
    end
  end

  def show
    @booking = Booking.find(params[:id])
    @passangers = Passenger.where(booking_id: @booking.id)
  end

  private

  def allowed_post_params
    params.require(:booking).permit(:flight_id, passengers_attributes: [:name, :email])
  end  
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @airport_list = Airport.all.map { |u| [u.name, u.id ]}
    @departure_day = Flight.all.map { |u| [u.start, u.start ]}

    unless params["/flights"].nil?
      maskapai = ['Garuda', 'Lion Air', 'City Link', 'Tom Flight']
      @available_flights = Flight.includes(:origin, :destination).where(origin: params["/flights"][:origin], destination: params["/flights"][:destination], start: params["/flights"][:departure_day]).map.with_index { |u, i| ["#{maskapai[i]} : Nonstop 4 hours flight from #{u.origin.name} to #{u.destination.name}", u.id]}
      @origin_fligt = Airport.find(params['/flights'][:origin])
      @destination_flight =  Airport.find(params['/flights'][:destination])
    end 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/passanger_helper.rb
module PassangerHelper
end

app/views/bookings/new.html.erb
<div class="info-booking">
  <div class="passanger_info">
    <h1>Booking</h1>
    <%= simple_form_for @booking do |f| %>
       <%= f.input :flight_id, as: :hidden, input_html: { value: params['booking'][:flight_id] }  %>
       <% params['booking'][:number_passanger].to_i.times do |i| %>
        <%= f.simple_fields_for :passengers, @booking.passengers.build do |fp| %>
          <h4><%= i + 1 %><%= (i + 1).ordinal %> passenger </h4>
          <div><%= fp.label "Name", required: true %></div>
          <div class="input-booking"><%= fp.input_field :name %></div>
          <div><%= fp.label "Email", required: true %></div>
          <div class="input-booking"><%= fp.input_field :email %></div>
        <% end %>
       <% end %>
      <div class="booking-submit"><%= f.submit %></div>
    <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="show-info">
  <div class="show">
    <% if notice %>
    <div class="alert">
      <%= notice %>
      <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
    </div> 
    <% end %>
    <h2 style="text-align: left">Booking for flight from <%= @booking.flight.origin.name %> to <%= @booking.flight.destination.name %> </h1>
    <h3 style="text-align: left"><%= @booking.flight.start.strftime("%d %B %Y") %> | Flight duration: <%= @booking.flight.flight_duration %> hours </h2>
    <div class="table-info">
      <% if @passangers.length > 1 %>
        <h4>Passengers list </h4>
        <% @passangers.each_with_index do |pas, i| %>
          <h5><%= i + 1 %><%= (i + 1).ordinal %> passenger</h5>
          <p>Name: <%= pas.name %></p>
          <p>Email: <%= pas.email %></p>
        <% end %>
      <% else %>
        <% @passangers.each_with_index do |pas, i| %>
        <p>Name: <%= pas.name %></p>
        <p>Email: <%= pas.email %></p>
      <% end %>
      <% end %>
     
    </div>
  </div>
</div>
      

app/views/flights/_available_flights.html.erb
<div class="available-flight">
  <div class="description">
    <h3 style="text-align: center">Outbound flight(s) from <%= @origin_fligt.name %> to <%= @destination_flight.name %></h3>
    <h4 style="text-align: center"><%= Date.parse(params["/flights"][:departure_day]).strftime("%d %B %Y") %></h4>
  </div>
  <div class="booking-form">
    <%= simple_form_for :booking, url: new_booking_path, method: :get do |f| %>
      <%= f.input :flight_id, as: :radio_buttons, collection: @available_flights, item_wrapper_tag: :div, item_wrapper_class: 'flight-choice', required: true %>
      <%= f.input :number_passanger, as: :hidden, input_html: { value: params["/flights"][:number_passanger] }  %>
      <div class="submit-button"><%= f.submit "Book Flight" %></div>
    <% end %>
  </div>
</div>

app/views/flights/index.html.erb
<% params["/flights"].nil? ? number_parameter = 1 : number_parameter = params["/flights"][:number_passanger] %>
<div class="container">
  <div class="index">
    <h1>Odin Flight</h1>
    <%= simple_form_for flights_path, method: :get do |f| %>
      <div class="from">
        <%= f.label "From" %>
        <div><%= f.select :origin, @airport_list, class: "form-select" %></div>
      </div>
      <div class="to">
        <%= f.label "To" %>
        <div><%= f.select :destination, @airport_list, selected: 2 %></div>
      </div>
      <div class="seats">
        <%= f.label "How many seat?" %>
        <div><%= f.select :number_passanger, 1..4, selected: number_parameter %></div>
      </div>
      <div class="date">
        <%= f.label "When?" %>
        <div><%= f.select :departure_day, @departure_day, selected: Date.today %></div>
      </div>
      <div class="search">
        <div><%= f.submit "Search" %></div>
      </div>
    <% end %>
  </div>
  <% unless params["/flights"].nil? %>
    <div class="outbound">
      <%= render 'flights/available_flights' %>
    </div>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar">
  <div class="brand"><%= link_to 'FLIGHT BOOKER', root_path %></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>